version: "3.7"
services:
    web:
        build: .
        image: app_laravel
        container_name: tomato-api
        restart: always
        expose:
            - 8080
        ports:
            - 8081:80
            - 443:443
        networks:
            - frontend

networks:
    frontend:
        name: app_network
